config/routes.rb
Rails.application.routes.draw do
  resources :products
  get 'simple_pages/tables'
  get 'simple_pages/chairs'
  get 'simple_pages/lamps'
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vintage Furniture</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>

    <!--Navigation-->
    <header class="container-full">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark container" role="navigation">
        <%= link_to "Vintage Furniture", root_path, class: "navbar-brand" %>
        <div class="burger">
          <button class="hamburger">&#9776;</button>
        </div>
        <!-- Collapse Navigation-->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item tables">
              <%= link_to "Tables", simple_pages_tables_path, class: "nav-link" %>
            </li>
            <li class="nav-item chairs">
              <%= link_to "Chairs", simple_pages_chairs_path, class: "nav-link" %>
            </li>
            <li class="nav-item lamps">
              <%= link_to "Lamps", simple_pages_lamps_path, class: "nav-link" %>
            </li>
            <li class="nav-item none-drop-link">
              <%= link_to "About", simple_pages_about_path, class: "nav-link" %>
            </li>
            <li class="nav-item none-drop-link">
              <%= link_to "Contact", simple_pages_contact_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a href="#"><i class="fas fa-search"></i></a>
            </li>
            <li class="nav-item">
              <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div> <!-- collapse close -->
      </nav> <!-- end nav container -->


      <!-- Dropdown Tables -->
      <div class="dropdown-tables dropdown-content hide-drop">
        <div class="links">
            <div class="links-col1">
              <li class="link-item">
               <%= link_to "Oak Rendered Table", simple_pages_tables_path, class: "nav-link roll", src: image_path("table1.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Stained Writing Table", simple_pages_tables_path, class: "nav-link roll", src: image_path("table2.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Large Slab Dinning Table", simple_pages_tables_path, class: "nav-link roll", src: image_path("table3.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Picnic Table", simple_pages_tables_path, class: "nav-link roll", src: image_path("table4.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Retro Storage Unit", simple_pages_tables_path, class: "nav-link roll", src: image_path("table5.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Oak Sideboard", simple_pages_tables_path, class: "nav-link roll", src: image_path("table6.jpg") %>
              </li>
            </div>
            <div class="links-col2">
              <li class="link-item">
                <%= link_to "Marble Top Dinning Table", simple_pages_tables_path, class: "nav-link roll", src: image_path("table7.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Wooden Banquet Table", simple_pages_tables_path, class: "nav-link roll", src: image_path("table8.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Stained Dinning Table", simple_pages_tables_path, class: "nav-link roll", src: image_path("table9.jpg") %>
              </li>
            </div>
        </div>
        <div id="image-display" class="show-img">
            <%= image_tag("table-preview.jpg", class: "img-fluid preview") %>
        </div>
      </div>

      <!-- Dropdown Chairs -->
      <div class="dropdown-chairs dropdown-content hide-drop">
        <div class="links">
            <div class="links-col1">
              <li class="link-item">
               <%= link_to "Chesterfield Chair Set", simple_pages_chairs_path, class: "nav-link roll", src: image_path("chair1.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Vintage Comfort Chair", simple_pages_chairs_path, class: "nav-link roll", src: image_path("chair2.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Oak Hall Chairs", simple_pages_chairs_path, class: "nav-link roll", src: image_path("chair3.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Upholstered Oak Chairs", simple_pages_chairs_path, class: "nav-link roll", src: image_path("chair4.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Classical Dinning Chairs", simple_pages_chairs_path, class: "nav-link roll", src: image_path("chair5.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Twin Armchairs", simple_pages_chairs_path, class: "nav-link roll", src: image_path("chair6.jpg") %>
              </li>
            </div>
            <div class="links-col2">
              <li class="link-item">
                <%= link_to "Dining Chairs", simple_pages_chairs_path, class: "nav-link roll", src: image_path("chair7.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Armchairs", simple_pages_chairs_path, class: "nav-link roll", src: image_path("chair8.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Gothic Dinnning Chairs", simple_pages_chairs_path, class: "nav-link roll", src: image_path("chair9.jpg") %>
              </li>
            </div>
        </div>
        <div id="image-display" class="show-img">
            <%= image_tag("chair-preview.jpg", class: "img-fluid preview") %>
        </div>
      </div>

      <!-- Dropdown Lamps -->
      <div class="dropdown-lamps dropdown-content hide-drop">
        <div class="links">
            <div class="links-col1">
              <li class="link-item">
               <%= link_to "Retro Element Bulbs", simple_pages_lamps_path, class: "nav-link roll", src: image_path("lamp1.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Metal Ceiling Lamps", simple_pages_lamps_path, class: "nav-link roll", src: image_path("lamp2.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Element Down Lights", simple_pages_lamps_path, class: "nav-link roll", src: image_path("lamp3.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Vintage Switch Lamps", simple_pages_lamps_path, class: "nav-link roll", src: image_path("lamp4.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Brass Up Lights", simple_pages_lamps_path, class: "nav-link roll", src: image_path("lamp5.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Retro Search Light", simple_pages_lamps_path, class: "nav-link roll", src: image_path("lamp6.jpg") %>
              </li>
            </div>
            <div class="links-col2">
              <li class="link-item">
                <%= link_to "Black Ceiling Lights", simple_pages_lamps_path, class: "nav-link roll", src: image_path("lamp7.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Vintage Metal Lamp", simple_pages_lamps_path, class: "nav-link roll", src: image_path("lamp8.jpg") %>
              </li>
              <li class="link-item">
                <%= link_to "Vintage Metal Lamp", simple_pages_lamps_path, class: "nav-link roll", src: image_path("lamp8.jpg") %>
              </li>
            </div>
        </div>
        <div id="image-display" class="show-img">
            <%= image_tag("lamp-preview.jpg", class: "img-fluid preview") %>
        </div>
      </div>

    </header>

    <%= yield %>

    <!-- footer section -->
    <footer class="container-nav">
      <div class="container">
        <div class="copy-right">
          <p>&copy; Vintage Furniture</p>
        </div>
        <div class="social-links">
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
        </div>
      </div>
    </footer>

    <script>


    </script>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="hero-section">
  <h1>Shop Comming Soon</h1>
  <p>Check back in a few weeks and bring your wallet!</p>
</div>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Colour</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= product.colour %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class: "hide-products" %>

<!-- Items Section -->
<section class="container thumbnails section-top">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-sm-12 col-md-6 col-lg-4 items-img">
        <%= image_tag product.image_url, alt: "Chair Section", class: "img-fluid" %>
        <span class="slide-bg"></span>
        <span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
        <%= link_to "", simple_pages_chairs_path, class: "title" %>
        <a href="#"><h1><%= product.name %></h1></a>
        <p><%= product.description %></p>
        <strong><%= product.price %></strong>
      </div>
    <% end %>
  </div>
</section>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="hero-section">
  <h1>Shop Comming Soon</h1>
  <p>Check back in a few weeks and bring your wallet!</p>
</div>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @product.colour %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/simple_pages/chairs.html.erb
<!-- Items Section -->
<section class="container thumbnails section-top">
	<div class="row">
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-chair1.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_tables_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-chair2.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_tables_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-chair3.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_tables_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-chair4.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_tables_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-chair5.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_tables_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-chair6.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_tables_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-chair7.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_tables_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-chair8.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_tables_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-chair5.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_tables_path, class: "title" %>
		</div>
	</div>
</section>

app/views/simple_pages/lamps.html.erb
<!-- Items Section -->
<section class="container thumbnails section-top">
	<div class="row">
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-lamp1.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-lamp2.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-lamp3.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-lamp4.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-lamp5.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-lamp6.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-lamp7.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-lamp8.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-lamp9.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
	</div>
</section>

app/views/simple_pages/tables.html.erb
<!-- Items Section -->
<section class="container thumbnails section-top">
	<div class="row">
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-table1.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-table2.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-table3.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-table4.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-table5.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-table6.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-table7.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-table8.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
		<div class="col-sm-12 col-md-6 col-lg-4 items-img">
			<%= image_tag "thumb-table9.jpg", alt: "Chair Section", class: "img-fluid" %>
			<span class="slide-bg"></span>
			<span class="title"><p class="proj-title"><i class="fas fa-shopping-cart"></i></p></span>
			<%= link_to "", simple_pages_chairs_path, class: "title" %>
		</div>
	</div>
</section>